version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: galeria
    ports:
      - '5432:5432'  
    networks:
      - galeria_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15432:80'  
    depends_on:
      - db
    networks:
      - galeria_network

  backend:
    build:
      dockerfile: Dockerfile
      context: ./galeria-backend  # Caminho para o backend
    container_name: galeria-backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'  # Porta de exposição do backend
    networks:
      - galeria_network
    environment:
      - POSTGRES_HOST=db  # Use o nome do serviço db como hostname

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./galeria-frontend  # Caminho para o frontend
    container_name: galeria-frontend
    restart: on-failure
    depends_on:
      - backend
    ports:
      - '3000:3000'  # Porta de exposição do frontend
    networks:
      - galeria_network
    expose:
      - 3000

networks:
  galeria_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
